feat: add loading while buy backer & adjust hexagon
DigitalExpert-IT/metaxot-campaign pull request #15
Opened 2024-04-26 09:26 UTC by Julius-745

Add Toast Loading While Buy Backer

2024-04-26 10:10 UTC, vickoeff requested changes
Commented

2024-04-26 10:10 UTC, vickoeff commented on src/routes/home/BakeOurProject.tsx
> +        await buyPackage.exec(Number(pkg.id)).then(() => toast.close(loadingToast))
If you try to implement toast at promises which have loading, success, error. You can try implement this Promise-Based Toast. Example code:

```
function PromiseBasedToastExample() {
  const toast = useToast()
  return (
    <Button
      onClick={() => {
        // Create an example promise that resolves in 5s
        const examplePromise = new Promise((resolve, reject) => {
          setTimeout(() => resolve(200), 5000)
        })

        // Will display the loading toast until the promise is either resolved
        // or rejected.
        toast.promise(examplePromise, {
          success: { title: 'Promise resolved', description: 'Looks great' },
          error: { title: 'Promise rejected', description: 'Something wrong' },
          loading: { title: 'Promise pending', description: 'Please wait' },
        })
      }}
    >
      Show Toast
    </Button>
  )
}
```

Or if in useAsyncCall have been handled the toast, try to custome that

2024-04-26 10:13 UTC, Julius-745 commented on src/routes/home/BakeOurProject.tsx
> +        await buyPackage.exec(Number(pkg.id)).then(() => toast.close(loadingToast))
i have try that before. when i ask you personally at DM i already use it but the success and error toast cant be removed. then i ask you is the wallet toast can be edit or not

2024-04-26 10:17 UTC, vickoeff commented on src/routes/home/BakeOurProject.tsx
> +        await buyPackage.exec(Number(pkg.id)).then(() => toast.close(loadingToast))
Ok. But why just only this async call did you add loading toast? If you fix it in useAsyncCall, other async call will be fixed in the same style/behavior. So let our UX have experience consistently

2024-04-30 04:40 UTC, vickoeff approved these changes
LGTM for now. But dont forget to improve quality later

2024-04-30 04:53 UTC, merged